import {
  IconBookmark,
  IconEdit,
  IconFolder,
  IconPlus,
  IconRefresh,
  IconTag,
  IconTrash,
  IconX,
} from '@tabler/icons-react';
import React, { useEffect, useState } from 'react';
import ApiSheet from '~/utils/apiSheet';

// --- Interfaces ---

interface Bookmark {
  id: string; // generated by sheet or frontend
  title: string;
  url: string;
  description: string;
  favicon: string;
  folder_id: string;
  tag_ids: string; // csv: "1,2,3"
  is_favorite: boolean;
  [key: string]: any;
}

interface Folder {
  id: string;
  name: string;
  slug: string;
  parent_id: string;
  icon: string;
  sort_order: number;
  [key: string]: any;
}

interface Tag {
  id: string;
  name: string;
  slug: string;
  color: string;
  [key: string]: any;
}

interface BookmarkMeta {
  id: string;
  bookmark_id: string;
  last_opened_at: string;
  open_count: number;
  note: string;
  [key: string]: any;
}

// --- Components ---

const InputField = ({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) => (
  <div className="mb-4">
    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">{label}</label>
    <input
      className="block w-full px-3 py-2 border border-gray-300 dark:border-slate-600 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm bg-white dark:bg-slate-700 text-gray-900 dark:text-white"
      {...props}
    />
  </div>
);

const CheckboxField = ({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) => (
  <div className="mb-4 flex items-center">
    <input type="checkbox" className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded" {...props} />
    <label className="ml-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{label}</label>
  </div>
);

export default function BookmarkAdmin() {
  const [apiKey, setApiKey] = useState('');
  const [scriptUrl, setScriptUrl] = useState('');
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [activeTab, setActiveTab] = useState<'bookmarks' | 'folders' | 'tags' | 'meta'>('bookmarks');
  const [api, setApi] = useState<ApiSheet | null>(null);

  // Data State
  const [bookmarks, setBookmarks] = useState<Bookmark[]>([]);
  const [folders, setFolders] = useState<Folder[]>([]);
  const [tags, setTags] = useState<Tag[]>([]);
  const [metas, setMetas] = useState<BookmarkMeta[]>([]);

  // Editing State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editItem, setEditItem] = useState<any | null>(null);
  const [formData, setFormData] = useState<any>({});

  useEffect(() => {
    const storedKey = localStorage.getItem('bookmark_api_key');
    const storedUrl = localStorage.getItem('bookmark_script_url');
    if (storedKey) setApiKey(storedKey);
    if (storedUrl) setScriptUrl(storedUrl);

    if (storedUrl) {
      initializeApi(storedUrl, storedKey || undefined);
    }
  }, []);
  useEffect(() => {
    if (api) {
      fetchData();
    }
  }, [api]);

  const initializeApi = (url: string, key?: string) => {
    try {
      const newApi = new ApiSheet(url, key);
      setApi(newApi);
      setIsAuthenticated(true);
    } catch (e) {
      console.error('Failed to init API', e);
    }
  };

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    localStorage.setItem('bookmark_api_key', apiKey);
    localStorage.setItem('bookmark_script_url', scriptUrl);
    initializeApi(scriptUrl, apiKey);
  };

  const handleLogout = () => {
    localStorage.removeItem('bookmark_api_key');
    localStorage.removeItem('bookmark_script_url');
    setApiKey('');
    setScriptUrl('');
    setIsAuthenticated(false);
    setApi(null);
    setBookmarks([]);
    setFolders([]);
    setTags([]);
  };

  const fetchData = async () => {
    if (!api) return;
    setIsLoading(true);
    try {
      // Parallel fetch for efficiency
      const [bookmarksRes, foldersRes, tagsRes] = await Promise.all([
        api.findAll<Bookmark[]>('Bookmarks'),
        api.findAll<Folder[]>('Folders'),
        api.findAll<Tag[]>('Tags'),
      ]);

      // Handle response structure depending on how findAll returns (array directly or object)
      // Adjust based on your ApiSheet implementation if it returns { data: ... } wrapped
      setBookmarks(Array.isArray(bookmarksRes) ? bookmarksRes : []);
      setFolders(Array.isArray(foldersRes) ? foldersRes : []);
      setTags(Array.isArray(tagsRes) ? tagsRes : []);
    } catch (error) {
      console.error('Error fetching data:', error);
      alert('Failed to fetch data. Check console for details.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!api) return;
    setIsLoading(true);

    const tableMap = {
      bookmarks: 'Bookmarks',
      folders: 'Folders',
      tags: 'Tags',
      meta: 'BookmarkMeta',
    };

    const tableName = tableMap[activeTab];

    try {
      if (editItem && editItem.id) {
        // Update
        await api.updateById(tableName, { ...formData, id: editItem.id });
      } else {
        // Create
        // Need to handle ID generation? Or let sheet handle it?
        // Assuming frontend needs to send ID or sheet auto-increments.
        // Ideally modify ApiSheet to return created object with ID.
        const newItem = { ...formData, id: crypto.randomUUID() };
        await api.create(tableName, newItem);
      }
      setIsModalOpen(false);
      setEditItem(null);
      setFormData({});
      await fetchData();
    } catch (error) {
      console.error('Save failed', error);
      alert('Save failed: ' + (error as Error).message);
    } finally {
      setIsLoading(false);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure?')) return;
    if (!api) return;

    const tableMap = {
      bookmarks: 'Bookmarks',
      folders: 'Folders',
      tags: 'Tags',
      meta: 'BookmarkMeta',
    };
    const tableName = tableMap[activeTab];

    setIsLoading(true);
    try {
      await api.deleteById(tableName, id);
      await fetchData();
    } catch (error) {
      console.error('Delete failed', error);
      alert('Delete failed');
    } finally {
      setIsLoading(false);
    }
  };

  const openModal = (item: any = null) => {
    setEditItem(item);
    setFormData(item || {});
    setIsModalOpen(true);
  };
  // Helper function to extract favicon from URL or icon data
  const extractFavicon = (linkElement: Element): string => {
    const iconAttr = linkElement.getAttribute('ICON');
    if (iconAttr && iconAttr.startsWith('data:image')) {
      return iconAttr;
    }

    const href = linkElement.getAttribute('HREF');
    if (href) {
      try {
        const url = new URL(href);
        return `https://www.google.com/s2/favicons?domain=${url.hostname}&sz=32`;
      } catch {
        return '';
      }
    }

    return '';
  };

  // Helper function to create slug from name
  const createSlug = (name: string): string => {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
  };

  // Helper function to generate random color
  const getRandomColor = (): string => {
    const colors = ['#EF4444', '#F59E0B', '#10B981', '#3B82F6', '#8B5CF6', '#EC4899', '#14B8A6', '#F97316'];
    return colors[Math.floor(Math.random() * colors.length)];
  };

  // Parse bookmarks HTML file
  const parseBookmarksHTML = (htmlContent: string) => {
    const parser = new DOMParser();
    const doc = parser.parseFromString(htmlContent, 'text/html');

    const newBookmarks: Bookmark[] = [];
    const newFolders: Folder[] = [];
    const folderMap = new Map<Element, string>(); // Map DL elements to folder IDs

    // Create root folder

    newFolders.push({
      id: 'root',
      name: 'Root',
      slug: 'root',
      parent_id: '',
      icon: '📁',
      sort_order: 0,
    });

    // Recursive function to process folders and bookmarks
    const processNode = (element: Element, parentFolderId: string, sortOrder: number = 0) => {
      const children = Array.from(element.children);
      let currentSortOrder = sortOrder;

      children.forEach((child) => {
        if (child.tagName === 'DT') {
          const h3 = child.querySelector('H3');
          const a = child.querySelector('A');
          const dl = child.querySelector('DL');

          // It's a folder
          if (h3 && dl) {
            const folderId = 'folder';
            const folderName = h3.textContent?.trim() || 'Untitled Folder';

            newFolders.push({
              id: folderId,
              name: folderName,
              slug: createSlug(folderName),
              parent_id: parentFolderId,
              icon: '📁',
              sort_order: currentSortOrder++,
            });

            folderMap.set(dl, folderId);
            processNode(dl, folderId, 0);
          }
          // It's a bookmark
          else if (a) {
            const href = a.getAttribute('HREF');
            const title = a.textContent?.trim() || 'Untitled';

            // Skip javascript bookmarklets and invalid URLs
            if (href && !href.startsWith('javascript:') && !href.startsWith('chrome://')) {
              newBookmarks.push({
                id: 'bookmark',
                title,
                url: href,
                description: '',
                favicon: extractFavicon(a),
                folder_id: parentFolderId,
                tag_ids: '',
                is_favorite: false,
              });
            }
          }
        }
        // Handle nested DL elements
        else if (child.tagName === 'DL') {
          const folderId = folderMap.get(child) || parentFolderId;
          processNode(child, folderId, 0);
        }
      });
    };

    // Find the main DL element and start processing
    const mainDL = doc.querySelector('DL');
    if (mainDL) {
      processNode(mainDL, 'root');
    }

    return { bookmarks: newBookmarks, folders: newFolders };
  };

  // Handle file upload
  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    setIsLoading(true);

    try {
      const text = await file.text();
      const { bookmarks: parsedBookmarks, folders: parsedFolders } = parseBookmarksHTML(text);

      for (const folder of parsedFolders) {
        await api?.create('Folders', folder);
      }
      for (const bookmark of parsedBookmarks) {
        await api?.create('Bookmarks', bookmark);
      }
      console.log('Parsed bookmarks:', parsedBookmarks.length);
      console.log('Parsed folders:', parsedFolders.length);
    } catch (err) {
      console.error('Error parsing bookmarks:', err);
    } finally {
      fetchData();
      setIsLoading(false);
    }
  };

  // Export data as JSON
  const exportAsJSON = () => {
    const data = {
      bookmarks,
      folders,
      tags,
      timestamp: new Date().toISOString(),
    };

    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bookmarks-export-${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (!isAuthenticated) {
    return (
      <div className="max-w-md mx-auto mt-20 p-6 bg-white dark:bg-slate-800 rounded-xl shadow-lg border border-gray-100 dark:border-slate-700">
        <h2 className="text-2xl font-bold mb-6 text-center text-gray-900 dark:text-white">Admin Login</h2>
        <form onSubmit={handleLogin} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Script URL / ID</label>
            <input
              type="text"
              required
              value={scriptUrl}
              onChange={(e) => setScriptUrl(e.target.value)}
              placeholder="https://script.google.com/..."
              className="block w-full px-3 py-2 border border-gray-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-gray-900 dark:text-white"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              API Key (Optional)
            </label>
            <input
              type="password"
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
              className="block w-full px-3 py-2 border border-gray-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-gray-900 dark:text-white"
            />
          </div>
          <button
            type="submit"
            className="w-full py-2 px-4 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium"
          >
            Connect
          </button>
        </form>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-slate-900 font-sans">
      {/* Navbar */}
      <div className="bg-white dark:bg-slate-800 shadow-sm border-b border-gray-200 dark:border-slate-700">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16">
            <div className="flex items-center">
              <span className="text-xl font-bold text-gray-900 dark:text-white ml-2">Bookmark Admin</span>
            </div>
            <div className="flex items-center space-x-4">
              <input
                type="file"
                accept=".html"
                onChange={handleFileUpload}
                className="block w-full text-sm text-gray-500
              file:mr-4 file:py-2 file:px-4
              file:rounded-md file:border-0
              file:text-sm file:font-semibold
              file:bg-blue-50 file:text-blue-700
              hover:file:bg-blue-100
              disabled:opacity-50 disabled:cursor-not-allowed"
              />

              <button
                onClick={fetchData}
                disabled={isLoading}
                className="p-2 text-gray-500 hover:text-blue-600 dark:text-gray-400 dark:hover:text-blue-400 transition-colors"
                title="Reload Data"
              >
                <IconRefresh className={`w-5 h-5 ${isLoading ? 'animate-spin' : ''}`} />
              </button>
              <button
                onClick={handleLogout}
                className="text-sm font-medium text-red-600 hover:text-red-700 dark:text-red-400"
              >
                Logout
              </button>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Tabs */}
        <div className="flex space-x-4 mb-6 overflow-x-auto pb-2 border-b border-gray-200 dark:border-slate-700">
          <button
            onClick={() => setActiveTab('bookmarks')}
            className={`flex items-center px-4 py-2 text-sm font-medium rounded-t-lg transition-colors whitespace-nowrap ${
              activeTab === 'bookmarks'
                ? 'bg-white dark:bg-slate-800 text-blue-600 dark:text-blue-400 border-b-2 border-blue-600'
                : 'text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200'
            }`}
          >
            <IconBookmark className="w-4 h-4 mr-2" />
            Bookmarks
          </button>
          <button
            onClick={() => setActiveTab('folders')}
            className={`flex items-center px-4 py-2 text-sm font-medium rounded-t-lg transition-colors whitespace-nowrap ${
              activeTab === 'folders'
                ? 'bg-white dark:bg-slate-800 text-blue-600 dark:text-blue-400 border-b-2 border-blue-600'
                : 'text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200'
            }`}
          >
            <IconFolder className="w-4 h-4 mr-2" />
            Folders
          </button>
          <button
            onClick={() => setActiveTab('tags')}
            className={`flex items-center px-4 py-2 text-sm font-medium rounded-t-lg transition-colors whitespace-nowrap ${
              activeTab === 'tags'
                ? 'bg-white dark:bg-slate-800 text-blue-600 dark:text-blue-400 border-b-2 border-blue-600'
                : 'text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200'
            }`}
          >
            <IconTag className="w-4 h-4 mr-2" />
            Tags
          </button>
        </div>

        {/* Action Bar */}
        <div className="flex justify-end mb-4">
          <button
            onClick={() => openModal()}
            className="flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium text-sm shadow-sm transition-colors"
          >
            <IconPlus className="w-4 h-4 mr-2" />
            Add New
          </button>
        </div>

        {/* Content Table */}
        <div className="bg-white dark:bg-slate-800 shadow-sm rounded-lg overflow-hidden border border-gray-200 dark:border-slate-700">
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200 dark:divide-slate-700">
              <thead className="bg-gray-50 dark:bg-slate-700/50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                    ID
                  </th>
                  {activeTab === 'bookmarks' && (
                    <>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Title
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        URL
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Tags
                      </th>
                    </>
                  )}
                  {activeTab === 'folders' && (
                    <>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Name
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Slug
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Parent
                      </th>
                    </>
                  )}
                  {activeTab === 'tags' && (
                    <>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Name
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Slug
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Color
                      </th>
                    </>
                  )}
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white dark:bg-slate-800 divide-y divide-gray-200 dark:divide-slate-700">
                {activeTab === 'bookmarks' &&
                  bookmarks.map((item) => (
                    <tr key={item.id} className="hover:bg-gray-50 dark:hover:bg-slate-700/30 transition-colors">
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400 font-mono">
                        {String(item.id || '').substring(0, 8)}...
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white">
                        {item.title}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-blue-500 hover:underline">
                        <a href={item.url} target="_blank" rel="noreferrer">
                          {item.url?.substring(0, 30)}...
                        </a>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                        {item.tag_ids?.split(',').map((tagId) => (
                          <span
                            key={tagId}
                            className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-gray-100 text-gray-800 dark:bg-slate-700 dark:text-gray-300 mr-1"
                          >
                            {tagId}
                          </span>
                        ))}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <button
                          onClick={() => openModal(item)}
                          className="text-blue-600 hover:text-blue-900 dark:text-blue-400 dark:hover:text-blue-300 mr-3"
                        >
                          <IconEdit className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleDelete(item.id)}
                          className="text-red-600 hover:text-red-900 dark:text-red-400 dark:hover:text-red-300"
                        >
                          <IconTrash className="w-4 h-4" />
                        </button>
                      </td>
                    </tr>
                  ))}
                {activeTab === 'folders' &&
                  folders.map((item) => (
                    <tr key={item.id} className="hover:bg-gray-50 dark:hover:bg-slate-700/30 transition-colors">
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400 font-mono">
                        {String(item.id || '').substring(0, 8)}...
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white flex items-center">
                        <IconFolder className="w-4 h-4 mr-2 text-yellow-500" /> {item.name}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                        {item.slug}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                        {item.parent_id || '-'}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <button
                          onClick={() => openModal(item)}
                          className="text-blue-600 hover:text-blue-900 dark:text-blue-400 dark:hover:text-blue-300 mr-3"
                        >
                          <IconEdit className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleDelete(item.id)}
                          className="text-red-600 hover:text-red-900 dark:text-red-400 dark:hover:text-red-300"
                        >
                          <IconTrash className="w-4 h-4" />
                        </button>
                      </td>
                    </tr>
                  ))}
                {activeTab === 'tags' &&
                  tags.map((item) => (
                    <tr key={item.id} className="hover:bg-gray-50 dark:hover:bg-slate-700/30 transition-colors">
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400 font-mono">
                        {String(item.id || '').substring(0, 8)}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white">
                        <span
                          className="inline-block w-3 h-3 rounded-full mr-2"
                          style={{ backgroundColor: item.color }}
                        ></span>
                        {item.name}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                        {item.slug}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400 font-mono">
                        {item.color}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <button
                          onClick={() => openModal(item)}
                          className="text-blue-600 hover:text-blue-900 dark:text-blue-400 dark:hover:text-blue-300 mr-3"
                        >
                          <IconEdit className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleDelete(item.id)}
                          className="text-red-600 hover:text-red-900 dark:text-red-400 dark:hover:text-red-300"
                        >
                          <IconTrash className="w-4 h-4" />
                        </button>
                      </td>
                    </tr>
                  ))}
              </tbody>
            </table>
            {((activeTab === 'bookmarks' && bookmarks.length === 0) ||
              (activeTab === 'folders' && folders.length === 0) ||
              (activeTab === 'tags' && tags.length === 0)) && (
              <div className="p-12 text-center text-gray-500 dark:text-gray-400">
                {isLoading ? 'Loading data...' : 'No items found. Click "Add New" to create one.'}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Modal */}
      {isModalOpen && (
        <div
          className="fixed inset-0 z-50 overflow-y-auto"
          aria-labelledby="modal-title"
          role="dialog"
          aria-modal="true"
        >
          <div className="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
            <div
              className="fixed inset-0 bg-gray-900 bg-opacity-75 transition-opacity"
              onClick={() => setIsModalOpen(false)}
            ></div>
            <span className="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">
              &#8203;
            </span>
            <div className="inline-block align-bottom bg-white dark:bg-slate-800 rounded-2xl text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg w-full">
              <div className="bg-white dark:bg-slate-800 px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                <div className="flex justify-between mb-4">
                  <h3 className="text-lg leading-6 font-medium text-gray-900 dark:text-white" id="modal-title">
                    {editItem ? `Edit ${activeTab.slice(0, -1)}` : `New ${activeTab.slice(0, -1)}`}
                  </h3>
                  <button onClick={() => setIsModalOpen(false)} className="text-gray-400 hover:text-gray-500">
                    <IconX className="w-5 h-5" />
                  </button>
                </div>

                <form onSubmit={handleSave} className="space-y-4">
                  {/* Dynamic Fields based on activeTab */}
                  {activeTab === 'bookmarks' && (
                    <>
                      <InputField
                        label="Title"
                        value={formData.title || ''}
                        onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                        required
                      />
                      <InputField
                        label="URL"
                        type="url"
                        value={formData.url || ''}
                        onChange={(e) => setFormData({ ...formData, url: e.target.value })}
                        required
                      />
                      <InputField
                        label="Description"
                        value={formData.description || ''}
                        onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                      />
                      <InputField
                        label="Favicon URL"
                        value={formData.favicon || ''}
                        onChange={(e) => setFormData({ ...formData, favicon: e.target.value })}
                      />

                      <div className="mb-4">
                        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                          Folder
                        </label>
                        <select
                          className="block w-full px-3 py-2 border border-gray-300 dark:border-slate-600 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500 sm:text-sm bg-white dark:bg-slate-700 text-gray-900 dark:text-white"
                          value={formData.folder_id || ''}
                          onChange={(e) => setFormData({ ...formData, folder_id: e.target.value })}
                        >
                          <option value="">No Folder</option>
                          {folders.map((f) => (
                            <option key={f.id} value={f.id}>
                              {f.name}
                            </option>
                          ))}
                        </select>
                      </div>

                      <InputField
                        label="Tags (comma separated IDs)"
                        value={formData.tag_ids || ''}
                        onChange={(e) => setFormData({ ...formData, tag_ids: e.target.value })}
                        placeholder="1, 2, 3"
                      />

                      <CheckboxField
                        label="Is Favorite"
                        checked={formData.is_favorite || false}
                        onChange={(e) => setFormData({ ...formData, is_favorite: e.target.checked })}
                      />
                    </>
                  )}

                  {activeTab === 'folders' && (
                    <>
                      <InputField
                        label="Name"
                        value={formData.name || ''}
                        onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                        required
                      />
                      <InputField
                        label="Slug"
                        value={formData.slug || ''}
                        onChange={(e) => setFormData({ ...formData, slug: e.target.value })}
                        required
                      />
                      <InputField
                        label="Parent ID"
                        value={formData.parent_id || ''}
                        onChange={(e) => setFormData({ ...formData, parent_id: e.target.value })}
                      />
                      <InputField
                        label="Icon"
                        value={formData.icon || ''}
                        onChange={(e) => setFormData({ ...formData, icon: e.target.value })}
                      />
                      <InputField
                        label="Sort Order"
                        type="number"
                        value={formData.sort_order || 0}
                        onChange={(e) => setFormData({ ...formData, sort_order: parseInt(e.target.value) })}
                      />
                    </>
                  )}

                  {activeTab === 'tags' && (
                    <>
                      <InputField
                        label="Name"
                        value={formData.name || ''}
                        onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                        required
                      />
                      <InputField
                        label="Slug"
                        value={formData.slug || ''}
                        onChange={(e) => setFormData({ ...formData, slug: e.target.value })}
                        required
                      />
                      <InputField
                        label="Color"
                        type="color"
                        value={formData.color || '#000000'}
                        onChange={(e) => setFormData({ ...formData, color: e.target.value })}
                        className="h-10"
                      />
                    </>
                  )}

                  <div className="mt-6 flex justify-end gap-3">
                    <button
                      type="button"
                      onClick={() => setIsModalOpen(false)}
                      className="px-4 py-2 bg-white dark:bg-slate-700 text-gray-700 dark:text-gray-200 rounded-lg border border-gray-300 dark:border-slate-600 hover:bg-gray-50 dark:hover:bg-slate-600 transition-colors font-medium text-sm"
                    >
                      Cancel
                    </button>
                    <button
                      type="submit"
                      className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium text-sm shadow-md"
                      disabled={isLoading}
                    >
                      {isLoading ? 'Saving...' : 'Save Changes'}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
